/**
 * AWS Bedrock proxy routes.
 *
 * Handles:
 *   - GET  /bedrock-proxy/models   (list foundation models + inference profiles)
 *   - POST /bedrock-proxy/invoke   (invoke model, streaming or non-streaming)
 */

import { env } from "node:process";

import {
  BedrockClient,
  ListFoundationModelsCommand,
  ListInferenceProfilesCommand,
} from "@aws-sdk/client-bedrock";

import {
  BedrockRuntimeClient,
  ConverseCommand,
  ConverseStreamCommand,
} from "@aws-sdk/client-bedrock-runtime";

import { fromNodeProviderChain, fromSSO } from "@aws-sdk/credential-providers";

import { getFirstHeaderValue } from "../utils/proxy-helpers.js";

import type {
  ConverseCommandInput,
  ConverseStreamCommandInput,
} from "@aws-sdk/client-bedrock-runtime";

import type { Express } from "express";

// ---- Bedrock helpers ----

const BEDROCK_REGION = env.BEDROCK_REGION || "";
const BEDROCK_PROFILE = env.BEDROCK_PROFILE || "";
const ADAPTIVE_THINKING_CAPABILITY_BY_MODEL_ID = new Map<string, boolean>();

function getBedrockRuntimeOptions(req: any): {
  region: string;
  profile: string;
  authMode: string;
} {
  const region =
    BEDROCK_REGION ||
    getFirstHeaderValue(req.headers["x-bedrock-region"])?.trim() ||
    "";
  const profile =
    BEDROCK_PROFILE ||
    getFirstHeaderValue(req.headers["x-bedrock-profile"])?.trim() ||
    "";
  const authMode =
    getFirstHeaderValue(req.headers["x-bedrock-auth-mode"])?.trim() ||
    "provider_chain";

  return { region, profile, authMode };
}

function createBedrockCredentials(profile: string, authMode: string) {
  if (authMode === "sso") {
    return fromSSO({ profile });
  }

  return fromNodeProviderChain({ profile });
}

function toInferenceProfileId(modelId: string, region: string): string {
  if (/^[a-z]{2}\.anthropic\./.test(modelId)) {
    return modelId;
  }

  const regionPrefix = region.split("-")[0];

  if (!regionPrefix) {
    throw new Error(
      "Bedrock region is not configured. Set BEDROCK_REGION or provide x-bedrock-region header.",
    );
  }

  return `${regionPrefix}.${modelId}`;
}

/**
 * Map an Anthropic Messages API content array entry to a Bedrock Converse
 * ContentBlock. Returns undefined for unknown block types so callers can filter.
 */
function anthropicContentToConverseBlock(c: any): any {
  if (c.type === "text") {
    return { text: c.text };
  }

  if (c.type === "image") {
    const b64: string = c.source.data;
    const mediaType: string = c.source.media_type; // e.g. "image/jpeg"
    const format = mediaType.split("/")[1]; // e.g. "jpeg"

    return {
      image: {
        format,
        source: { bytes: Buffer.from(b64, "base64") },
      },
    };
  }

  if (c.type === "tool_use") {
    return {
      toolUse: {
        toolUseId: c.id,
        name: c.name,
        input: c.input,
      },
    };
  }

  if (c.type === "tool_result") {
    const resultContent =
      typeof c.content === "string"
        ? [{ text: c.content }]
        : Array.isArray(c.content)
          ? c.content.map((rc: any) =>
              rc.type === "text"
                ? { text: rc.text }
                : { text: JSON.stringify(rc) },
            )
          : [{ text: JSON.stringify(c.content) }];

    return {
      toolResult: {
        toolUseId: c.tool_use_id,
        content: resultContent,
      },
    };
  }

  if (c.type === "thinking") {
    // Bedrock validates that replayed thinking blocks include an authentic
    // signature generated by Claude. If signature is missing, omit the block
    // to avoid request validation failures.
    if (typeof c.signature !== "string" || c.signature.length === 0) {
      return undefined;
    }

    return {
      reasoningContent: {
        reasoningText: {
          text: c.thinking || "",
          signature: c.signature,
        },
      },
    };
  }

  if (c.type === "redacted_thinking") {
    return {
      reasoningContent: {
        redactedContent: {
          data: c.data || "",
        },
      },
    };
  }

  // Fallback: render unknown block types as text so we don't silently drop them.

  return { text: JSON.stringify(c) };
}

/**
 * Convert a stop reason from the Bedrock Converse StopReason enum to the
 * Anthropic Messages API stop_reason string.
 */
function toAnthropicStopReason(stopReason: string | undefined): string {
  switch (stopReason) {
    case "tool_use":
      return "tool_use";
    case "max_tokens":
      return "max_tokens";
    case "stop_sequence":
      return "stop_sequence";
    case "end_turn":
    default:
      return "end_turn";
  }
}

function randomMsgId(): string {
  return "msg_" + Math.random().toString(36).substring(2, 10);
}

function normalizeAdaptiveEffort(value: unknown):
  | "low"
  | "medium"
  | "high"
  | "xhigh"
  | "max"
  | undefined {
  if (typeof value !== "string") {
    return undefined;
  }

  const normalized = value.trim().toLowerCase();
  if (
    normalized === "low" ||
    normalized === "medium" ||
    normalized === "high" ||
    normalized === "xhigh" ||
    normalized === "max"
  ) {
    return normalized;
  }

  if (normalized === "minimal" || normalized === "none") {
    return "low";
  }

  return undefined;
}

function effortFromBudget(
  budgetTokens: unknown,
  maxTokens: unknown,
): "low" | "medium" | "high" | "xhigh" | "max" {
  const budget =
    typeof budgetTokens === "number" && Number.isFinite(budgetTokens)
      ? Math.max(1, budgetTokens)
      : 0;
  const limit =
    typeof maxTokens === "number" && Number.isFinite(maxTokens)
      ? Math.max(1, maxTokens)
      : 8192;
  const ratio = budget > 0 ? budget / limit : 0.5;

  if (ratio >= 0.95) {
    return "max";
  }

  if (ratio >= 0.85) {
    return "xhigh";
  }

  if (ratio >= 0.7) {
    return "high";
  }

  if (ratio >= 0.35) {
    return "medium";
  }

  return "low";
}

function inferAdaptiveThinkingCapability(value: unknown): boolean | undefined {
  if (typeof value !== "string" || value.trim().length === 0) {
    return undefined;
  }

  const id = value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");

  if (
    id.includes("claude-sonnet-5") ||
    id.includes("claude-opus-4-7") ||
    id.includes("claude-opus-5") ||
    id.includes("claude-opus-4-8") ||
    id.includes("claude-mythos-5")
  ) {
    return true;
  }

  if (id.includes("claude-sonnet-4-6")) {
    return false;
  }

  return undefined;
}

function cacheAdaptiveThinkingCapability(
  modelId: unknown,
  modelName?: unknown,
): void {
  if (typeof modelId !== "string" || modelId.trim().length === 0) {
    return;
  }

  const byId = inferAdaptiveThinkingCapability(modelId);
  const byName = inferAdaptiveThinkingCapability(modelName);
  const inferred = byName ?? byId;

  if (typeof inferred === "boolean") {
    ADAPTIVE_THINKING_CAPABILITY_BY_MODEL_ID.set(modelId.toLowerCase(), inferred);
  }
}

function supportsAdaptiveThinking(modelId: string, resolvedModelId: string): boolean {
  const raw = modelId.toLowerCase();
  const resolved = resolvedModelId.toLowerCase();

  if (ADAPTIVE_THINKING_CAPABILITY_BY_MODEL_ID.has(raw)) {
    return ADAPTIVE_THINKING_CAPABILITY_BY_MODEL_ID.get(raw) === true;
  }

  if (ADAPTIVE_THINKING_CAPABILITY_BY_MODEL_ID.has(resolved)) {
    return ADAPTIVE_THINKING_CAPABILITY_BY_MODEL_ID.get(resolved) === true;
  }

  const inferredRaw = inferAdaptiveThinkingCapability(raw);
  if (typeof inferredRaw === "boolean") {
    return inferredRaw;
  }

  const inferredResolved = inferAdaptiveThinkingCapability(resolved);
  if (typeof inferredResolved === "boolean") {
    return inferredResolved;
  }

  return false;
}

function buildBedrockModelRequestFields(
  anthropicBody: any,
  rawModelId: string,
  resolvedModelId: string,
): Record<string, unknown> | undefined {
  if (!anthropicBody?.thinking) {
    return undefined;
  }

  const thinking = anthropicBody.thinking;

  if (!supportsAdaptiveThinking(rawModelId, resolvedModelId)) {
    return { thinking };
  }

  const requestedType =
    typeof thinking?.type === "string" ? thinking.type.toLowerCase() : "";

  if (requestedType === "disabled") {
    return { thinking };
  }

  const configuredEffort = normalizeAdaptiveEffort(
    anthropicBody?.output_config?.effort,
  );

  const derivedEffort = effortFromBudget(
    thinking?.budget_tokens,
    anthropicBody?.max_tokens,
  );

  return {
    thinking: { type: "adaptive" },
    output_config: {
      effort: configuredEffort || derivedEffort,
    },
  };
}

export function registerBedrockRoutes(
  app: Express,
  _options: { verbose?: boolean } = {},
): void {
  // ---- Bedrock: list models ----
  app.get("/bedrock-proxy/models", async (req, res) => {
    try {
      const runtime = getBedrockRuntimeOptions(req);
      if (!runtime.region || !runtime.profile) {
        return res.status(400).json({
          error:
            "Bedrock is not configured. Set BEDROCK_REGION and BEDROCK_PROFILE environment variables or provide Bedrock fallback settings in the UI.",
        });
      }

      const client = new BedrockClient({
        region: runtime.region,
        credentials: createBedrockCredentials(
          runtime.profile,
          runtime.authMode,
        ),
      });

      // Fetch Foundation Models
      const fmResponse = await client.send(
        new ListFoundationModelsCommand({ byProvider: "Anthropic" }),
      );

      const models = (fmResponse.modelSummaries || [])
        .filter((m) => m.modelLifecycle?.status === "ACTIVE")
        .map((m) => {
          cacheAdaptiveThinkingCapability(m.modelId, m.modelName);

          return { id: m.modelId, name: m.modelName };
        });

      // Fetch Inference Profiles (to support Cross-Region inference)
      try {
        const ipResponse = await client.send(
          new ListInferenceProfilesCommand({}),
        );
        const profiles = (ipResponse.inferenceProfileSummaries || [])
          .filter((p) => p.status === "ACTIVE")
          // Only show Anthropic-compatible profiles since our proxy format is 'anthropic'
          .filter(
            (p) =>
              p.inferenceProfileId?.includes("anthropic") ||
              p.inferenceProfileName?.toLowerCase().includes("anthropic"),
          )
          .map((p) => ({
            id: p.inferenceProfileId || "",
            name: `${p.inferenceProfileName || "Unnamed Profile"} (Profile)`,
          }))
          .map((profile) => {
            cacheAdaptiveThinkingCapability(profile.id, profile.name);

            return profile;
          });

        models.push(...profiles);
      } catch (ipErr: unknown) {
        // AccessDeniedException is expected when the credential chain lacks
        // bedrock:ListInferenceProfiles — silently skip in that case.
        const errName =
          ipErr && typeof ipErr === "object" && "name" in ipErr
            ? (ipErr as { name: string }).name
            : "";
        if (errName !== "AccessDeniedException") {
          console.warn(
            "Failed to list Bedrock inference profiles:",
            ipErr instanceof Error ? ipErr.message : String(ipErr),
          );
        }

        // Non-fatal, proceed with just foundation models
      }

      res.json({ models });
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      console.error("Bedrock models discovery error:", message);
      res
        .status(502)
        .json({ error: `Failed to list Bedrock models: ${message}` });
    }
  });

  // ---- Bedrock: invoke model ----
  app.post("/bedrock-proxy/invoke", async (req, res) => {
    try {
      const runtime = getBedrockRuntimeOptions(req);
      if (!runtime.region || !runtime.profile) {
        return res.status(400).json({
          error:
            "Bedrock is not configured. Set BEDROCK_REGION and BEDROCK_PROFILE environment variables or provide Bedrock fallback settings in the UI.",
        });
      }

      const body = req.body;
      if (!body || typeof body !== "object") {
        return res.status(400).json({ error: "Missing request body" });
      }

      const rawModelId = body.model;
      if (
        typeof rawModelId !== "string" ||
        (!rawModelId.startsWith("anthropic.") &&
          !/^[a-z]{2}\.anthropic\./.test(rawModelId))
      ) {
        return res.status(400).json({
          error: `Invalid model ID: '${String(rawModelId || "")}'. Must be an Anthropic Bedrock model ID.`,
        });
      }

      const modelId = toInferenceProfileId(rawModelId, runtime.region);
      const wantsStreaming = body.stream === true;

      // Strip transport fields not used by the Converse API
      const { model: _model, stream: _stream, ...anthropicBody } = body;

      const client = new BedrockRuntimeClient({
        region: runtime.region,
        credentials: createBedrockCredentials(
          runtime.profile,
          runtime.authMode,
        ),
      });

      // --- Build Converse messages ---
      const messages = (anthropicBody.messages || []).map((m: any) => ({
        role: m.role as "user" | "assistant",
        content: Array.isArray(m.content)
          ? m.content
              .map(anthropicContentToConverseBlock)
              .filter((block: any) => block !== undefined)
          : [{ text: m.content as string }],
      }));

      // --- System prompt ---
      const system = anthropicBody.system
        ? [{ text: anthropicBody.system as string }]
        : undefined;

      // --- Inference config (mapped from Anthropic field names) ---
      const inferenceConfig: ConverseCommandInput["inferenceConfig"] = {};
      if (anthropicBody.max_tokens) {
        inferenceConfig.maxTokens = anthropicBody.max_tokens;
      }

      if (anthropicBody.temperature !== undefined) {
        inferenceConfig.temperature = anthropicBody.temperature;
      }

      if (anthropicBody.top_p !== undefined) {
        inferenceConfig.topP = anthropicBody.top_p;
      }

      if (anthropicBody.stop_sequences) {
        inferenceConfig.stopSequences = anthropicBody.stop_sequences;
      }

      // --- Tool config ---
      let toolConfig: ConverseCommandInput["toolConfig"] = undefined;
      if (anthropicBody.tools && anthropicBody.tools.length > 0) {
        toolConfig = {
          tools: anthropicBody.tools.map((t: any) => ({
            toolSpec: {
              name: t.name,
              description: t.description,
              inputSchema: { json: t.input_schema },
            },
          })),
        };
        if (anthropicBody.tool_choice) {
          const tc = anthropicBody.tool_choice;
          if (tc.type === "tool") {
            toolConfig.toolChoice = { tool: { name: tc.name } };
          } else if (tc.type === "any") {
            toolConfig.toolChoice = { any: {} };
          } else {
            toolConfig.toolChoice = { auto: {} };
          }
        }
      }

      const converseParams = {
        modelId,
        messages,
        system,
        inferenceConfig:
          Object.keys(inferenceConfig).length > 0 ? inferenceConfig : undefined,
        toolConfig,
        additionalModelRequestFields: buildBedrockModelRequestFields(
          anthropicBody,
          rawModelId,
          modelId,
        ),
      };

      if (wantsStreaming) {
        // ---- Streaming path: ConverseStream ----
        const command = new ConverseStreamCommand(
          converseParams as ConverseStreamCommandInput,
        );
        const response = await client.send(command);

        res.status(200);
        res.setHeader("Content-Type", "text/event-stream");
        res.setHeader("Cache-Control", "no-cache");
        res.setHeader("Connection", "keep-alive");
        res.setHeader("Access-Control-Allow-Origin", "*");
        res.flushHeaders();

        // Emit message_start in Anthropic SSE format
        res.write(
          `data: ${JSON.stringify({
            type: "message_start",
            message: {
              id: randomMsgId(),
              type: "message",
              role: "assistant",
              model: modelId,
              content: [],
              usage: { input_tokens: 0, output_tokens: 0 },
            },
          })}\n\n`,
        );

        if (response.stream) {
          const startedBlocks = new Set<number>();
          for await (const event of response.stream) {
            if (event.contentBlockStart) {
              // ContentBlockStart has no text member — text blocks emit their
              // first content via a contentBlockDelta, not a start event.
              // We emit a content_block_start for tool_use only.
              const start: any = event.contentBlockStart.start;
              const index = event.contentBlockStart.contentBlockIndex ?? 0;
              startedBlocks.add(index);

              if (start?.toolUse) {
                res.write(
                  `data: ${JSON.stringify({
                    type: "content_block_start",
                    index,
                    content_block: {
                      type: "tool_use",
                      id: start.toolUse.toolUseId,
                      name: start.toolUse.name,
                      input: {},
                    },
                  })}\n\n`,
                );
              } else if (start?.reasoningContent !== undefined) {
                const signature =
                  typeof start?.reasoningContent?.signature === "string"
                    ? start.reasoningContent.signature
                    : typeof start?.reasoningContent?.reasoningText
                          ?.signature === "string"
                      ? start.reasoningContent.reasoningText.signature
                      : undefined;

                res.write(
                  `data: ${JSON.stringify({
                    type: "content_block_start",
                    index,
                    content_block: {
                      type: "thinking",
                      thinking: "",
                      ...(signature ? { signature } : {}),
                    },
                  })}\n\n`,
                );
              } else {
                // Text / image / unknown start — emit a generic text block start
                res.write(
                  `data: ${JSON.stringify({
                    type: "content_block_start",
                    index,
                    content_block: { type: "text", text: "" },
                  })}\n\n`,
                );
              }
            } else if (event.contentBlockDelta) {
              const delta: any = event.contentBlockDelta.delta;
              const index = event.contentBlockDelta.contentBlockIndex ?? 0;

              if (!startedBlocks.has(index)) {
                startedBlocks.add(index);

                const inferredType =
                  delta?.toolUse !== undefined ? "tool_use" : "text";

                res.write(
                  `data: ${JSON.stringify({
                    type: "content_block_start",
                    index,
                    content_block:
                      inferredType === "text"
                        ? { type: "text", text: "" }
                        : { type: "tool_use", id: "", name: "", input: {} },
                  })}\n\n`,
                );
              }

              if (delta?.text !== undefined) {
                res.write(
                  `data: ${JSON.stringify({
                    type: "content_block_delta",
                    index,
                    delta: { type: "text_delta", text: delta.text },
                  })}\n\n`,
                );
              } else if (delta?.reasoningContent?.text !== undefined) {
                res.write(
                  `data: ${JSON.stringify({
                    type: "content_block_delta",
                    index,
                    delta: {
                      type: "thinking_delta",
                      thinking: delta.reasoningContent.text,
                    },
                  })}\n\n`,
                );
              } else if (
                typeof delta?.reasoningContent?.signature === "string" ||
                typeof delta?.reasoningContent?.reasoningText?.signature ===
                  "string"
              ) {
                const signature =
                  typeof delta.reasoningContent.signature === "string"
                    ? delta.reasoningContent.signature
                    : delta.reasoningContent.reasoningText.signature;

                res.write(
                  `data: ${JSON.stringify({
                    type: "content_block_delta",
                    index,
                    delta: {
                      type: "signature_delta",
                      signature,
                    },
                  })}\n\n`,
                );
              } else if (
                delta?.reasoningContent?.redactedContent !== undefined
              ) {
                res.write(
                  `data: ${JSON.stringify({
                    type: "content_block_delta",
                    index,
                    delta: {
                      type: "redacted_thinking_delta",
                      data: delta.reasoningContent.redactedContent,
                    },
                  })}\n\n`,
                );
              } else if (delta?.toolUse?.input !== undefined) {
                res.write(
                  `data: ${JSON.stringify({
                    type: "content_block_delta",
                    index,
                    delta: {
                      type: "input_json_delta",
                      partial_json: delta.toolUse.input,
                    },
                  })}\n\n`,
                );
              }
            } else if (event.contentBlockStop) {
              res.write(
                `data: ${JSON.stringify({
                  type: "content_block_stop",
                  index: event.contentBlockStop.contentBlockIndex ?? 0,
                })}\n\n`,
              );
            } else if (event.messageStop) {
              const stop_reason = toAnthropicStopReason(
                event.messageStop.stopReason,
              );
              res.write(
                `data: ${JSON.stringify({
                  type: "message_delta",
                  delta: { stop_reason, stop_sequence: null },
                })}\n\n`,
              );
              res.write(
                `data: ${JSON.stringify({ type: "message_stop" })}\n\n`,
              );
            } else if (event.metadata?.usage) {
              // Emit updated usage in message_start-compatible form (best effort)
              const usage = event.metadata.usage;
              res.write(
                `data: ${JSON.stringify({
                  type: "message_delta",
                  usage: {
                    input_tokens: usage.inputTokens ?? 0,
                    output_tokens: usage.outputTokens ?? 0,
                  },
                })}\n\n`,
              );
            }
          }
        }

        res.end();
      } else {
        // ---- Non-streaming path: Converse ----
        const command = new ConverseCommand(
          converseParams as ConverseCommandInput,
        );
        const response = await client.send(command);

        const outMsg = response.output?.message;
        const content = (outMsg?.content || []).map((c: any) => {
          if (c.text !== undefined) {
            return { type: "text", text: c.text };
          }

          if (c.reasoningContent?.reasoningText) {
            return {
              type: "thinking",
              thinking: c.reasoningContent.reasoningText.text || "",
              ...(typeof c.reasoningContent.reasoningText.signature === "string"
                ? { signature: c.reasoningContent.reasoningText.signature }
                : {}),
            };
          }

          if (c.reasoningContent?.redactedContent) {
            return {
              type: "redacted_thinking",
              data: c.reasoningContent.redactedContent.data || "",
            };
          }

          if (c.toolUse) {
            return {
              type: "tool_use",
              id: c.toolUse.toolUseId,
              name: c.toolUse.name,
              input: c.toolUse.input,
            };
          }

          return { type: "text", text: JSON.stringify(c) };
        });

        res.json({
          id: randomMsgId(),
          type: "message",
          role: "assistant",
          model: modelId,
          content,
          stop_reason: toAnthropicStopReason(response.stopReason),
          stop_sequence: null,
          usage: {
            input_tokens: response.usage?.inputTokens ?? 0,
            output_tokens: response.usage?.outputTokens ?? 0,
          },
        });
      }
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      console.error("Bedrock invoke error:", message);

      const status =
        message.includes("expired") || message.includes("credentials")
          ? 401
          : 502;

      if (!res.headersSent) {
        res
          .status(status)
          .json({ error: `Bedrock invocation failed: ${message}` });
      } else {
        res.write(
          `data: ${JSON.stringify({
            type: "error",
            error: { type: "server_error", message },
          })}\n\n`,
        );
        res.end();
      }
    }
  });
}
